config/routes.rb
Rails.application.routes.draw do

  get 'models/index'

  get 'models/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'disabled' => 'home#disabled', as: :disabled
  get 'contact' => 'home#contact', as: :contact
  get 'models/:sex/:category(/:letter)' => 'models#index', as: :models
  get 'models/vision' => 'models#vision', as: :vision
  get 'models/paradise' => 'models#paradise', as: :paradise
  get 'model/:id/book' => 'models#show', as: :model, defaults: { photo_type: 'book' }
  get 'model/:id/polaroids' => 'models#show', as: :model_polaroids, defaults: { photo_type: 'polaroids' }

  root 'home#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :models
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :sex
  belongs_to :category



  scope :boys_mainboard, -> {
    sex = Sex.find_by_name('Boy')
    category = Category.find_by_name('Mainboard')
    where(sex: sex, category: category)
  }

  scope :boys_development, -> {
    sex = Sex.find_by_name('Boy')
    category = Category.find_by_name('Development')
    where(sex: sex, category: category)
  }

  scope :girls_mainboard, -> {
    sex = Sex.find_by_name('Girl')
    category = Category.find_by_name('Mainboard')
    where(sex: sex, category: category)
  }

  scope :girls_development, -> {
    sex = Sex.find_by_name('Girl')
    category = Category.find_by_name('Development')
    where(sex: sex, category: category)
  }

  scope :vision, -> {
    category = Category.find_by_name('Vision')
    where(category: category)
  }

  scope :paradise, -> {
    category = Category.find_by_name('Paradise')
    where(category: category)
  }

  scope :girls_paradise, -> {
    sex = Sex.find_by_name('Girl')
    category = Category.find_by_name('Paradise')
    where(sex: sex, category: category)
  }

  scope :boys_paradise, -> {
    sex = Sex.find_by_name('Boy')
    category = Category.find_by_name('Paradise')
    where(sex: sex, category: category)
  }

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true
  has_many :polaroids, dependent: :destroy
  accepts_nested_attributes_for :polaroids, allow_destroy: true

  has_attached_file :comp_card
  has_attached_file :pdf
  validates_attachment_content_type :comp_card, content_type: ['application/pdf']
  validates_attachment_content_type :pdf, content_type: ['application/pdf']

  def instagram_url
    "https://instagram.com/#{instagram}"
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :model

  has_attached_file :file, styles: { full: ['1280x960', :jpg], index: ['386x565>', :jpg] }
  dropzone_item data: :file,
                file_size: :file_file_size,
                title: :file_file_name,
                url: :data_url,
                container_id: :model_id,
                position: :position


  validates_attachment_content_type :file, content_type: ['image/png', 'image/jpeg', 'image/jpg']

  def orientation
    Paperclip::Geometry.from_file(self.file).horizontal? ? 'horizontal' : 'vertical'
  end

end

app/models/polaroid.rb
class Polaroid < ActiveRecord::Base
  belongs_to :model

  has_attached_file :file, styles: { full: ['1280x960', :jpg], index: ['386x565>', :jpg] }
  dropzone_item data: :file,
                file_size: :file_file_size,
                title: :file_file_name,
                url: :data_url,
                container_id: :model_id,
                position: :position


  validates_attachment_content_type :file, content_type: ['image/png', 'image/jpeg', 'image/jpg']

  def orientation
    Paperclip::Geometry.from_file(self.file).horizontal? ? 'horizontal' : 'vertical'
  end

end

app/models/sex.rb
class Sex < ActiveRecord::Base
  has_many :models
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_many :slider_photos
  accepts_nested_attributes_for :slider_photos, allow_destroy: true
end

app/models/slider_photo.rb
class SliderPhoto < ActiveRecord::Base
  belongs_to :slider
  has_attached_file :file, styles: { full: ['1280x960', :jpg] }
  validates_attachment_content_type :file, content_type: ['image/png', 'image/jpeg', 'image/jpg']
  dropzone_item data: :file,
                file_size: :file_file_size,
                title: :file_file_name,
                url: :data_url,
                container_id: :slider_id,
                position: :position
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_filter :redirect_to_disabled_page

  private

  def redirect_to_disabled_page
    redirect_to(disabled_path) unless action_name == 'disabled'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def fullscreen
    render layout: 'fullscreen'
  end

  def home
    @slider = Slider.first
  end

  def contact
    @no_footer = true;
  end

  def disabled
    render layout: 'fullscreen'
  end

end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model_and_photos, only: [:show]

  def index
    @sex = Sex.find_by_name(params[:sex].capitalize)
    @category = Category.find_by_name(params[:category].capitalize)
    @models = Model.where(category: @category, sex: @sex)
  end

  def vision
    @models = Model.vision
    render template: 'models/index'
  end

  def paradise
    @models = Model.paradise
    render template: 'models/index'
  end

  def show
    render layout: 'fullscreen'
  end

  private
  def set_model_and_photos
    @model = Model.find(params[:id])
    case params[:photo_type]
      when 'polaroids'
        @photos = @model.polaroids
      else
        @photos = @model.photos
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def instagram_url
    "https://instagram.com/universemanagement"
  end

  def facebook_url
    "https://facebook.com/UniverseManagement"
  end

  def blog_url
    "https://tumblr.com"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/application/_dropzone.html.erb
<div id="dropzone_<%= method %>_<%= cycle(*(1..999).to_a, name: method) %>" class="dropzone">
  <span class="notice"><%=t 'dropzone.drag_or_click' %></span>
  <% object.send(method).each_with_index do |dropzone_object, index| %>
    <%= hidden_field_tag "#{ object_name }[#{ method }_attributes][#{ index }][id]", dropzone_object.id %>
  <% end %>
</div>

<% unless options[:hint].blank? %>
  <p class="inline-hints dropzone-hint"><%= options[:hint] %></p>
<% end %>

<script>
  (function() {
    Dropzone.autoDiscover = false;

    var mockFiles = <%= render_mock_dropzone_files(object.send(method)) %>;
    var mockFilesCount = mockFiles.length;
    var fileIndex = 0;
    var dropzone_id = "#dropzone_<%= method %>_<%= current_cycle(method) %>";
    var dropzone = new Dropzone(dropzone_id, {
      url: '<%= raw upload_dropzone_path(container_id: (object.new_record? ? nil : object.id), container_type: object.class, dropzone_class: object.send(method).klass.to_s) %>',
      addRemoveLinks: true,
      dictCancelUpload: '<%=t "dropzone.cancel" %>',
      dictRemoveFile: '<%=t "dropzone.remove" %>',
      maxFiles: <%= defined?(max_files) ? '1' : 'null' %>,
      sending: function(file, xhr, formData) {
        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').prop('content'));
      },
      success: function(file, data) {
        file.id = data.id;
        $(dropzone_id).append('<input type="hidden" name="<%= object_name %>[<%= method %>_attributes][' + $(file.previewElement).attr('data-index') + '][id]" value="' + file.id + '" />');
        $(file.previewElement).attr('data-id', data.id);
        $(file.previewElement).attr('data-url', data.url);
        return file.previewElement.classList.add("dz-success");
      },
      removedfile: function(file) {
        $(file.previewElement).remove();
        $(dropzone_id).sortable('refresh');
        $.ajax({
          url: '<%= raw destroy_dropzone_path(container_id: (object.new_record? ? nil : object.id), container_type: object.class, dropzone_class: object.send(method).klass.to_s) %>' + '&id=' + file.id,
          type: 'DELETE',
          success: function(data) {
            $(dropzone_id).find('input[value="' + file.id + '"]').remove();
            if (data.result != 'ok') {
              alert('Ошибка удаления фото. Пожалуйста, перезагрузите форму.');
            }
          }
        });
      }
    });

    $(dropzone_id).sortable({
      items: '.dz-preview',
      placeholder: 'sortable-placeholder',
      scroll: false
    });

    var func = function(file) {
      var id = file.id || '';
      var filename = file.name || '';
      var title = file.title || filename;
      var index = file.index || fileIndex++;
      var type = file.type || undefined;
      var img = file.previewElement.children[0].children[2];

      if( (type && !/image/.test(type)) || !/\.(jpe?g|png|gif)/i.test(img.src) ) {
        img.src = ''; // не показываем битый img
        img.alt = ''; // не показываем лишнюю подпись дял битого img
      }

      file._captionLabel = Dropzone.createElement('<p>Название:</p>');
      file._captionBox = Dropzone.createElement('<input id="album_photos_' + id + '_title" class="dropzone-caption" type="text" name="<%= object_name %>[<%= method %>_attributes][' + index + '][title]" value="' + title + '" />');
      file.previewElement.appendChild(file._captionLabel);
      file.previewElement.appendChild(file._captionBox);

      $(file.previewElement).attr('data-id', id);
      $(file.previewElement).attr('data-index', index);
    };

    var generate_dropzone_position_elements = function() {
      var position = 0;
      $(dropzone_id + ' .dz-preview').each(function() {
        var index = $(this).attr('data-index');
        var id = $(this).attr('data-id');
        $(dropzone_id).prepend('<input type="hidden" name="<%= object_name %>[<%= object.send(method).klass.model_name.element %>_ids][]" value="' + id + '"/>');
        $(dropzone_id).append('<input type="hidden" name="<%= object_name %>[<%= method %>_attributes][' + index + '][<%= object.send(method).klass.send("dropzone_field", :position) %>]" value="' + (position++) + '" />');
      });
    };

    dropzone.on('addedfile', func);

    for (var i = 0; i < mockFiles.length; i++) {
      var mockFile = mockFiles[i];
      dropzone.options.addedfile.call(dropzone, mockFile);
      if (mockFile.url) {
        dropzone.options.thumbnail.call(dropzone, mockFile, mockFile.url);
        $(mockFile.previewElement).attr('data-url', mockFile.url);
      }
      func(mockFile);
    }

    $('form').submit(function(e) {
      if (dropzone.getQueuedFiles().length > 0 || dropzone.getUploadingFiles().length > 0) {
        if (confirm("<%=t 'dropzone.are_you_sure' %>")) {
          generate_dropzone_position_elements();
        } else {
          e.preventDefault();
        }
      } else {
        generate_dropzone_position_elements();
      }
    });

    window.<%= method %>_dropzone = dropzone;
  })();
</script>

app/views/home/contact.html.erb
<div class="ui container stackable grid">
  <div class="sixteen wide center aligned column">
    <%= image_tag 'universe_icon_logo.png', class: 'ui small centered image' %>
    <div class="ui list">
      <div class="item">
        <i class="envelope icon"></i>
        agency@universemanagement.net
      </div>
    </div>
  </div>
</div>

app/views/home/disabled.html.erb
<h1>Server is down. Please contact your provider.</h1>

app/views/home/fullscreen.html.erb
<style>
  body {
    background: url("<%= image_url 'fondo_full_2.jpg' %>") no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    height: 100%;
    width: 100%;
    display: table;
    vertical-align: middle;
  }

  #middle-cell {
    display: table-cell;
    vertical-align: middle;
    margin: auto;
    text-align: center;
  }

  #middle-block {
    margin: auto;
    background-color: rgba(0,0,0, 0) !important;
  }

  #middle-menu {
    color: white;
    justify-content: center;
    margin-top: 0 !important;
  }
  .ui.text.menu .item {
    color: rgba(255, 255, 255, 0.81);
  }

  .ui.link.menu .item:hover, .ui.menu .dropdown.item:hover, .ui.menu .link.item:hover, .ui.menu a.item:hover {
    color: white;
  }
  .ui.menu .ui.dropdown .menu > .item {
    color: rgba(255, 255, 255, 0.81) !important;
    text-align: center;
  }
  .ui.menu .ui.dropdown .menu > .item:hover {
    color: white !important;
  }
  .ui.menu .dropdown.item .menu {
    background: rgba(0,0,0, 1) !important;
    left: -35px;
  }
</style>

<div id="middle-cell">
  <div class="ui black inverted compact segment" id="middle-block">
    <%= image_tag 'logo_blanco.png', class: 'ui centered medium image' %>
    <div class="ui centered text inverted menu" id="middle-menu">
      <%= link_to "HOME", home_path, class: 'item' %>
      <div class="ui dropdown item">
        BOYS
        <div class="menu">
          <%= link_to "MAINBOARD", models_path(sex: 'boy', category: 'mainboard'), class: 'item' %>
          <%= link_to "DEVELOPMENT", models_path(sex: 'boy', category: 'development'), class: 'item' %>
        </div>
      </div>
      <div class="ui dropdown item">
        GIRLS
        <div class="menu">
          <%= link_to "MAINBOARD", models_path(sex: 'girl', category: 'mainboard'), class: 'item' %>
          <%= link_to "DEVELOPMENT", models_path(sex: 'girl', category: 'development'), class: 'item' %>
        </div>
      </div>
      <%= link_to "VISION", vision_path, class: 'item' %>
      <div class="item">
        CONTACT
      </div>
    </div>
  </div>
</div>

app/views/home/home.html.erb
<div class="ui container">
  <ul id="home-slider">
    <% @slider.slider_photos.each do |photo| %>
        <li class="home-slide">
          <%= image_tag photo.file.url(:full) %>
        </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Universe Management</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= render partial: 'shared/header' %>

<%= yield %>

<%= render partial: 'shared/footer' %>

</body>
</html>

app/views/layouts/fullscreen.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Universe Management</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/models/_model_card.html.erb
<div class="ui column model-column" style="display: block;">
  <%= link_to model_path(model) do %>
      <div class="ui image">
        <div class="ui dimmer model-dimmer">
          <div class="content">
            <div class="center">
              <p class="model-name"><%= model.name.upcase %></p>
            </div>
          </div>
        </div>
        <%= image_tag model.photos.find_by_position(0).file.url if model.photos.find_by_position(0) %>
      </div>
  <% end %>
</div>

app/views/models/index.html.erb
<div class="ui container stackable grid">
  <div class="row" style="padding: 1rem;">
    <%= "#{params[:sex].capitalize if params[:sex]} / #{params[:category].capitalize if params[:category]}" %>
  </div>
  <div class="row">
    <div class="ui three column doubling stackable masonry grid">
      <% @models.each do |model| %>
        <%= render partial: 'model_card', locals: {model: model} %>
      <% end %>
    </div>
  </div>
</div>

app/views/models/show.html.erb
<div class="model-slider">
  <div class="single-slide first-slide model-info-wrapper">
    <div class="model-info">
      <p class="model-info-item"><%= params[:photo_type].upcase %></p>
      <p class="model-info-item"><span><%= @model.name if @model.name %></span></p>
      <div class="ui divider"></div>
      <p class="model-info-item"><span>HEIGHT</span> <%= @model.height if @model.height %> </p>
      <p class="model-info-item"><span>CHEST</span> <%= @model.chest if @model.chest %> </p>
      <p class="model-info-item"><span>WAIST</span> <%= @model.waist if @model.waist %> </p>
      <p class="model-info-item"><span>HIP</span> <%= @model.hip if @model.hip %> </p>
      <p class="model-info-item"><span>JEANS</span> <%= @model.jeans if @model.jeans %> </p>
      <p class="model-info-item"><span>SHOE</span> <%= @model.shoe if @model.shoe %> </p>
      <p class="model-info-item"><span>HAIR</span> <%= @model.hair if @model.hair %> </p>
      <p class="model-info-item"><span>EYES</span> <%= @model.eyes if @model.eyes %> </p>
      <div class="ui hidden divider"></div>

      <p class="model-info-item">
        <%= link_to "+INSTAGRAM", @model.instagram_url, target: :_blank if @model.instagram %>
      </p>
      <% case params[:photo_type] %>
      <% when 'polaroids' %>
          <p class="model-info-item">
            <%= link_to "+BOOK", model_path(@model) %>
          </p>
          <p class="model-info-item">
            <span>-POLAROIDS</span>
          </p>

      <% else %>
          <p class="model-info-item">
            <span>-BOOK</span>
          </p>
          <p class="model-info-item">
            <%= link_to "+POLAROIDS", model_polaroids_path(@model) %>
          </p>
      <% end %>
      <p class="model-info-item">
        <%= link_to "+VIDEO", @model.video, class: 'popup-youtube' if @model.video %>
      </p>
      <p class="model-info-item">
        <%= link_to "+DOWNLOAD COMP CARD", @model.comp_card.url if @model.comp_card.url %>
      </p>
      <p class="model-info-item">
        <%= link_to "+DOWNLOAD PDF", @model.pdf.url if @model.pdf.url %>
      </p>
      <div class="ui hidden divider"></div>
      <%= image_tag 'universe_icon_logo.png', class: 'ui mini image' %>
    </div>
  </div>
  <% @photos.sort_by { |p| p.position }.each do |photo| %>
      <% if photo.orientation == 'horizontal' %>
          <div></div>
          <div class="single-slide">
            <%= image_tag photo.file.url %>
          </div>
      <% else %>
          <div class="single-slide">
            <%= image_tag photo.file.url %>
          </div>
      <% end %>
  <% end %>
  <div class="single-slide last-slide model-info-wrapper">
    <div class="model-info" style="text-align: center">
      <%= link_to "BACK TO MODELS", models_index_path(sex: @model.sex.name, category: @model.category.name), style: 'color: black;' %>
    </div>
  </div>
</div>

<i class="ui large left chevron icon" id="prevSlide"></i>
<i class="ui large right chevron icon" id="nextSlide"></i>
<%= link_to models_index_path(sex: @model.sex.name, category: @model.category.name), id: 'closeModel' do %>
    <i class="ui large close icon"></i>
<% end %>

<div class="ui mobile only tablet only stackable one column grid">
  <div class="column">
    <div class="ui divider"></div>
    <div class="model-info">
      <p class="model-info-item"><%= params[:photo_type].upcase %></p>
      <p class="model-info-item"><span><%= @model.name if @model.name %></span></p>
      <div class="ui divider"></div>
      <p class="model-info-item"><span>HEIGHT</span> <%= @model.height if @model.height %> </p>
      <p class="model-info-item"><span>CHEST</span> <%= @model.chest if @model.chest %> </p>
      <p class="model-info-item"><span>WAIST</span> <%= @model.waist if @model.waist %> </p>
      <p class="model-info-item"><span>HIP</span> <%= @model.hip if @model.hip %> </p>
      <p class="model-info-item"><span>JEANS</span> <%= @model.jeans if @model.jeans %> </p>
      <p class="model-info-item"><span>SHOE</span> <%= @model.shoe if @model.shoe %> </p>
      <p class="model-info-item"><span>HAIR</span> <%= @model.hair if @model.hair %> </p>
      <p class="model-info-item"><span>EYES</span> <%= @model.eyes if @model.eyes %> </p>
      <div class="ui hidden divider"></div>

      <p class="model-info-item">
        <%= link_to "+INSTAGRAM", @model.instagram_url, target: :_blank if @model.instagram %>
      </p>
      <% case params[:photo_type] %>
      <% when 'polaroids' %>
          <p class="model-info-item">
            <%= link_to "+BOOK", model_path(@model) %>
          </p>
          <p class="model-info-item">
            <span>-POLAROIDS</span>
          </p>

      <% else %>
          <p class="model-info-item">
            <span>-BOOK</span>
          </p>
          <p class="model-info-item">
            <%= link_to "+POLAROIDS", model_polaroids_path(@model) %>
          </p>
      <% end %>
      <p class="model-info-item">
        <%= link_to "+VIDEO", @model.video, class: 'popup-youtube' if @model.video %>
      </p>
      <p class="model-info-item">
        <%= link_to "+DOWNLOAD COMP CARD", @model.comp_card.url if @model.comp_card.url %>
      </p>
      <p class="model-info-item">
        <%= link_to "+DOWNLOAD PDF", @model.pdf.url if @model.pdf.url %>
      </p>
      <div class="ui hidden divider"></div>
      <%= image_tag 'universe_icon_logo.png', class: 'ui mini image' %>
    </div>
    <div class="ui divider"></div>
  </div>
  <% @photos.sort_by { |p| p.position }.each do |photo| %>
          <div class="column">
            <%= image_tag photo.file.url, class: 'ui image' %>
            <div class="ui divider"></div>
          </div>
  <% end %>
  <div class="column">
    <div class="model-info" style="text-align: center">
      <%= link_to "BACK TO MODELS", models_index_path(sex: @model.sex.name, category: @model.category.name), style: 'color: black; font-weight: bold;' %>
    </div>
    <div class="ui divider"></div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="ui container">
  <div class="ui centered horizontal list" style="display: block; text-align: center; margin: 40px auto;">
    <div class="item">
      <%= image_tag 'universe_icon_logo.png', class: 'ui mini image' unless @no_footer %>
    </div>
    <div class="item">© 2017, UNIVERSE MANAGEMENT</div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="ui container">
  <div class="ui stackable one column grid">
    <div class="computer only column">
      <div class="ui text menu" id="header-menu">
        <div class="item">
          <%= image_tag 'logo_negro.png', class: 'ui medium image logo' %>
        </div>
        <%= link_to "HOME", root_path, class: 'item' %>
        <div class="ui dropdown item">
          BOYS
          <div class="menu">
            <%= link_to "MAINBOARD", models_path(sex: 'boys', category: 'mainboard'), class: 'item' %>
            <%= link_to "DEVELOPMENT", models_path(sex: 'boys', category: 'development'), class: 'item' %>
          </div>
        </div>
        <div class="ui dropdown item">
          GIRLS
          <div class="menu">
            <%= link_to "MAINBOARD", models_path(sex: 'girls', category: 'mainboard'), class: 'item' %>
            <%= link_to "DEVELOPMENT", models_path(sex: 'girls', category: 'development'), class: 'item' %>
          </div>
        </div>
        <%= link_to "VISION", vision_path, class: 'item' %>
        <%= link_to "PARADISE", paradise_path, class: 'item' %>
        <%= link_to "BLOG", blog_url, class: 'item' %>
        <%= link_to "CONTACT", contact_path, class: 'item' %>
        <%= link_to "INSTAGRAM", instagram_url, class: 'item', target: :_blank %>
        <%= link_to "FACEBOOK", facebook_url, class: 'item', target: :_blank %>
      </div>
    </div>
    <div class="mobile only tablet only row center aligned">
      <div class="ui text vertical menu" id="header-menu-small">
        <div class="item">
          <%= image_tag 'logo_negro.png', class: 'ui medium image logo' %>
        </div>
        <%= link_to "HOME", root_path, class: 'item' %>
        <div class="ui dropdown item">
          BOYS
          <div class="menu">
            <%= link_to "MAINBOARD", models_path(sex: 'boys', category: 'mainboard'), class: 'item' %>
            <%= link_to "DEVELOPMENT", models_path(sex: 'boys', category: 'development'), class: 'item' %>
          </div>
        </div>
        <div class="ui dropdown item">
          GIRLS
          <div class="menu">
            <%= link_to "MAINBOARD", models_path(sex: 'girls', category: 'mainboard'), class: 'item' %>
            <%= link_to "DEVELOPMENT", models_path(sex: 'girls', category: 'development'), class: 'item' %>
          </div>
        </div>
        <%= link_to "VISION", vision_path, class: 'item' %>
        <%= link_to "PARADISE", paradise_path, class: 'item' %>
        <%= link_to "BLOG", blog_url, class: 'item' %>
        <%= link_to "CONTACT", contact_path, class: 'item' %>
        <%= link_to "INSTAGRAM", instagram_url, class: 'item', target: :_blank %>
        <%= link_to "FACEBOOK", facebook_url, class: 'item', target: :_blank %>
      </div>
    </div>
  </div>
</div>